type: forgan
MODEL:
  dsc:
    type: TCN
    hidden_size: 0
    num_layers: 0
    kernel_size: 0
    
  gen:
    type: TCN
    noise_size: 0
    hidden_size: 0
    num_layers: 0
    kernel_size: 0

  history_window_size: 0
  horizon: 0
  loss: ls
  lr: 0.001
  optimizer: rms
TRAIN:
  batch_size: 256
  d_iter: 2
  early_stopping_tolerance: 5000
  file_log: true
  n_samples: 100
  n_steps: 100000
  screen_log: true
  skip_val: 0
  val_interval: 10
